use customers_order_payment;

# Task 1: Order and Sales Analysis
# Analyzed order status and sales to uncover fulfillment and revenue trends.
SELECT 
    order_status, 
    COUNT(order_id) AS total_orders,
    SUM(order_amount) AS total_revenue,
    ROUND(AVG(order_amount), 2) AS avg_order_value
FROM customer_orders
GROUP BY order_status
ORDER BY total_orders DESC;

/*Key Insights:
Helps understand how many orders are being delivered vs. pending vs. shipped.

Shows how much revenue is generated by each status category.

If most revenue comes from “delivered” orders, it indicates good fulfillment.

A high number of "pending" orders may indicate operational delays or issues.*/